---
version: 2.0

jobs:
  unit_tests:
    docker:
    - image: circleci/golang:1.14.1
    steps:
    - checkout
    - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
    - run: make test
    - run:
        command: bash <(curl -s https://codecov.io/bash)
        when: always
    - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
            - "/home/circleci/.cache/go-build"
  release:
    docker:
      - image: circleci/golang:1.14.1
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u="$QUAY_TOKEN" -p="$QUAY_TOKEN" quay.io
      - run: hack/parse-changelog.sh $CIRCLE_TAG CHANGELOG.md > /tmp/release_notes.txt
      - run: curl -sL https://git.io/goreleaser | bash -s -- --release-notes <(cat /tmp/release_notes.txt)
  release_dry:
    docker:
      - image: circleci/golang:1.14.1
    steps:
      - checkout
      - setup_remote_docker
      - run: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist --snapshot

workflows:
  version: 2
  default:
    jobs:
      - unit_tests:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release_dry:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

      - release:
          requires:
            - unit_tests
            - release_dry
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
